# Clé du projet local
sonar.projectKey=my-local-project
sonar.projectName=My Local Project
sonar.projectVersion=1.0
sonar.token=

# URL du serveur local
sonar.host.url=http://localhost:9000

# Sources à analyser
sonar.sources=src

# Ignorer ton fichier constants pour la duplication
sonar.cpd.exclusions=src/renderer/constants/**/*.ts